# Generated by Django 4.2.29 on 2026-03-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('horas_juego', models.PositiveIntegerField(default=0)),
                ('nivel', models.CharField(choices=[('bronce', 'Bronce'), ('plata', 'Plata'), ('oro', 'Oro'), ('elite', 'Elite')], default='bronce', max_length=10)),
            ],
            options={
                'db_table': 'equipo',
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('calificacion_esrb', models.CharField(choices=[('E', 'Everyone'), ('E10+', 'Everyone 10+'), ('T', 'Teen'), ('M', 'Mature 17+'), ('AO', 'Adults Only 18+'), ('RP', 'Rating Pending')], max_length=5)),
                ('estudio', models.CharField(max_length=200)),
                ('num_jugadores', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('fisico', 'Físico'), ('digital', 'Digital')], max_length=10)),
                ('existencias', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'juego',
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'plataforma',
            },
        ),
        migrations.CreateModel(
            name='Trofeo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('puntos', models.PositiveIntegerField()),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trofeos', to='api.juego')),
            ],
            options={
                'db_table': 'trofeo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte')], max_length=5)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('edad', models.PositiveSmallIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('comuna', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_trabajo', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('redes_sociales', models.JSONField(blank=True, default=dict)),
                ('tipo_usuario', models.CharField(choices=[('entrenador', 'Entrenador'), ('atleta', 'Atleta'), ('administrativo', 'Administrativo'), ('proveedor', 'Proveedor')], max_length=20)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('acudiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menores_a_cargo', to='api.usuario')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atletas', to='api.equipo')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioTrofeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtencion', models.DateField(auto_now_add=True)),
                ('trofeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trofeo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'usuario_trofeo',
                'unique_together': {('usuario', 'trofeo')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='trofeos',
            field=models.ManyToManyField(blank=True, through='api.UsuarioTrofeo', to='api.trofeo'),
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_agendamiento', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('agendada', 'Agendada'), ('activa', 'Activa'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='agendada', max_length=10)),
                ('puntos_xp_asignados', models.PositiveIntegerField(default=0)),
                ('hora_real_inicio', models.TimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=255, null=True)),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_arbitradas', to='api.usuario')),
                ('atleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_como_atleta', to='api.usuario')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='api.equipo')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.juego')),
            ],
            options={
                'db_table': 'sesion',
            },
        ),
        migrations.AddField(
            model_name='juego',
            name='plataformas',
            field=models.ManyToManyField(related_name='juegos', to='api.plataforma'),
        ),
        migrations.CreateModel(
            name='EquipoTrofeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtencion', models.DateField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipo')),
                ('trofeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trofeo')),
            ],
            options={
                'db_table': 'equipo_trofeo',
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='api.juego'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='trofeos',
            field=models.ManyToManyField(blank=True, through='api.EquipoTrofeo', to='api.trofeo'),
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('teclado', 'Teclado'), ('mouse', 'Mouse'), ('gamepad', 'Gamepad'), ('instrumento', 'Instrumento Musical'), ('volante', 'Volante'), ('otro', 'Otro')], max_length=15)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles', to='api.plataforma')),
            ],
            options={
                'db_table': 'control',
            },
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_total', models.PositiveSmallIntegerField(default=1)),
                ('direccion_ip', models.GenericIPAddressField()),
                ('mac_utp5', models.CharField(max_length=17)),
                ('mac_inalambrica', models.CharField(max_length=17)),
                ('total_controles', models.PositiveSmallIntegerField(default=0)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.plataforma')),
            ],
            options={
                'db_table': 'consola',
            },
        ),
        migrations.AddConstraint(
            model_name='sesion',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('atleta__isnull', True), ('equipo__isnull', False)), models.Q(('atleta__isnull', False), ('equipo__isnull', True)), _connector='OR'), name='sesion_equipo_o_atleta'),
        ),
        migrations.AlterUniqueTogether(
            name='equipotrofeo',
            unique_together={('equipo', 'trofeo')},
        ),
    ]
